refactored

diff --git a/scripts/docker-umount b/scripts/docker-umount
--- a/scripts/docker-umount
+++ b/scripts/docker-umount
@@ -1,55 +1,49 @@
 #!/bin/bash
 set -o errexit -o pipefail
 
-#todo check if inside docker-geek
-
 function show_usage() {
-    >&2 echo "Unmount a dir or file previously bind-mounted to an running container."
+    >&2 echo "Unmount a dir in host or a running container."
     >&2 echo ""
     >&2 echo "Usage:"
-    >&2 echo "  ${0##*/} CONTAINER:TARGET_PATH"
+    >&2 echo "  ${0##*/} MOUNT_POINT"
+    >&2 echo "  ${0##*/} CONTAINER_ID_OR_NAME MOUNT_POINT"
+    >&2 echo "  ${0##*/} CONTAINER_ID_OR_NAME:MOUNT_POINT"
     >&2 echo ""
-    >&2 echo "CONTAINER:"
-    >&2 echo "  The container id or name"
-    >&2 echo ""
-    >&2 echo "TARGET_PATH:"
-    >&2 echo "  The mount point, can be a dir or file. Must start with /"
+    >&2 echo "MOUNT_POINT:"
+    >&2 echo "  The mounted dir"
     >&2 echo ""
     exit 1
 }
 
-TARGET_ID=""; TARGET_PATH=""
+[[ ! $1 || $1 == --help ]] && show_usage
 
-while [[ $# -gt 0 ]]; do
-    case $1 in
-    -*)
-            show_usage
-            ;;
+if [[ $2 ]]; then
+    ID=$1
+    MOUNT_POINT=$2
+elif [[ $1 == *:* ]]; then
+    ID=${1%%:*}
+    MOUNT_POINT=${1#*:}
+else
+    ID=""
+    MOUNT_POINT=$1
+fi
 
-    *:/*)
-            TARGET_PATH=${1#*:}
-            [[ $TARGET_PATH != /* ]] && show_usage
-            TARGET_ID=${1%%:*}
-            [[ ! $TARGET_ID ]] && show_usage
-            ;;
-    *)
-            show_usage
-            ;;
-    esac
-    shift
-done
+[[ $MOUNT_POINT != /* ]] && { >&2 echo "${0##*/}: mount point must start with /"; exit 1; }
 
-TARGET_ROOTFS=$(docker-rootfs-of-container "$TARGET_ID")
+ROOTFS=""; [[ $ID ]] && ROOTFS=$(docker-rootfs-of-container "$ID")
 
-# Notes: 
-# - The -v /var/lib/docker:/var/lib/docker:rshared is for bind-mounting across containers later
-# - The --pid=host --network=host ...=host are just for launching container faster
+[[ $IS_DOCKER_GEEK ]] && exec umount "$ROOTFS$MOUNT_POINT"
 
-[[ $IS_DOCKER_GEEK ]] && exec umount "$TARGET_ROOTFS$TARGET_PATH"
+# Enter host namespace to do umount. The reason use nsenter-dockerd is that
+# it definitely contains proper umount util.
+#
+# Notes:
+# - The --network=host --ipc=host --uts=host are optional, just for launching container faster
+
+#todo -1 just umount one time, otherwise repeat umount until failure,
+#todo support --all
 
 exec docker run --rm \
     --privileged --userns=host \
     --pid=host --network=host --ipc=host --uts=host \
-    -v /var/lib/docker:/var/lib/docker:rshared \
-    --entrypoint umount \
-    osexp2000/bind-mount "$TARGET_ROOTFS$TARGET_PATH"
+    osexp2000/nsenter-dockerd umount "$ROOTFS$MOUNT_POINT"
